### PR TITLE
Updated copyright date

### PR DESCRIPTION
**Pull request by wyndchyme**
Truly largest and most significant pull request of all time

### CODE REVIEW

**Comment by selene-selene** [comment]
I hope you know you are gonna be forgotten when you die, you are genuinely scum beneath everything that exists alongside the others, just like me, except I'll try to make an exception and make myself be a worshipped figure, and you're gonna be forgotten after 2 generations, while my monument made of pure gold will be lay there, and your ashes would be miniscule compared to the statue that represented my status as a somewhat worshipped figure. I hope you know how miniscule you would be compared to me in the afterlife. Be it Heaven or Hell, Tartarus or Elysium, Valhalla or Hel, I hope you know that even beyond reincarnation and the end itself, I will be a true and personal hater, only here to spite you out of hate, even going as far to try and learn voodoo just place curses upon you just because it would genuinely be funny.

And even then, that is not enough, no matter what, I'm always gonna be here, hating and hating, loathing your existence beyond what God himself can imagine, taking it to extreme lengths, not even things that would be traumatically affect you, that would be too easy, I want to see you always have at least a clogged nose three times a week, I want you to wake up with a calf cramp at least four times a week, I want to see you at least break your something expensive of your belongings like your monitor to your GPU itself to break at least once a month, and I want you to gain 2x the weight you'd gain from eating, and the obvious option for you of losing weight would be hindered to at least 25% the speed of what it is now, slowing your metabolism enough to make it process an entire dish of spaghetti in half a decade.

**Comment by TheProgrammer1337** [comment]
Thank you Selene.

**Comment by wyndchyme** [comment]
> I hope you know you are gonna be forgotten when you die, you are genuinely scum beneath everything that exists alongside the others, just like me, except I'll try to make an exception and make myself be a worshipped figure, and you're gonna be forgotten after 2 generations, while my monument made of pure gold will be lay there, and your ashes would be miniscule compared to the statue that represented my status as a somewhat worshipped figure. I hope you know how miniscule you would be compared to me in the afterlife. Be it Heaven or Hell, Tartarus or Elysium, Valhalla or Hel, I hope you know that even beyond reincarnation and the end itself, I will be a true and personal hater, only here to spite you out of hate, even going as far to try and learn voodoo just place curses upon you just because it would genuinely be funny.
> 
> And even then, that is not enough, no matter what, I'm always gonna be here, hating and hating, loathing your existence beyond what God himself can imagine, taking it to extreme lengths, not even things that would be traumatically affect you, that would be too easy, I want to see you always have at least a clogged nose three times a week, I want you to wake up with a calf cramp at least four times a week, I want to see you at least break your something expensive of your belongings like your monitor to your GPU itself to break at least once a month, and I want you to gain 2x the weight you'd gain from eating, and the obvious option for you of losing weight would be hindered to at least 25% the speed of what it is now, slowing your metabolism enough to make it process an entire dish of spaghetti in half a decade.

linus torvalds is that you

**Comment by wyndchyme** [comment]
that isn't even a copypasta i'm like 90% sure selene typed that up 😭

**Comment by Cracko298** [comment]
I accept both arguments.

**Comment by pizza-beep** [comment]
> that isn't even a copypasta i'm like 90% sure selene typed that up 😭

Selene moment

**Pull request merged**
